module.exports = {
  "tables": [{
    "name": "strapi_core_store_settings",
    "indexes": [],
    "foreignKeys": [],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "key",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "value",
      "type": "text",
      "args": ["longtext"],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "type",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "environment",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {"name": "tag", "type": "string", "args": [], "defaultTo": null, "notNullable": false, "unsigned": false}]
  }, {
    "name": "strapi_webhooks",
    "indexes": [],
    "foreignKeys": [],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "url",
      "type": "text",
      "args": ["longtext"],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "headers",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "events",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {"name": "enabled", "type": "boolean", "args": [], "defaultTo": null, "notNullable": false, "unsigned": false}]
  }, {
    "name": "admin_permissions",
    "indexes": [{
      "name": "admin_permissions_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "admin_permissions_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "admin_permissions_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "admin_permissions_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "action",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "subject",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "properties",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "conditions",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "admin_users",
    "indexes": [{
      "name": "admin_users_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "admin_users_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "admin_users_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "admin_users_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "firstname",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "lastname",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "username",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "email",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "password",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "reset_password_token",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "registration_token",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "is_active",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "blocked",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "prefered_language",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "admin_roles",
    "indexes": [{
      "name": "admin_roles_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "admin_roles_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "admin_roles_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "admin_roles_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "code",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "description",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "strapi_api_tokens",
    "indexes": [{
      "name": "strapi_api_tokens_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "strapi_api_tokens_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "strapi_api_tokens_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "strapi_api_tokens_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "description",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "type",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "access_key",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "last_used_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "expires_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "lifespan",
      "type": "bigInteger",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "strapi_api_token_permissions",
    "indexes": [{
      "name": "strapi_api_token_permissions_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "strapi_api_token_permissions_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "strapi_api_token_permissions_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "strapi_api_token_permissions_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "action",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "strapi_transfer_tokens",
    "indexes": [{
      "name": "strapi_transfer_tokens_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "strapi_transfer_tokens_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "strapi_transfer_tokens_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "strapi_transfer_tokens_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "description",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "access_key",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "last_used_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "expires_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "lifespan",
      "type": "bigInteger",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "strapi_transfer_token_permissions",
    "indexes": [{
      "name": "strapi_transfer_token_permissions_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "strapi_transfer_token_permissions_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "strapi_transfer_token_permissions_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "strapi_transfer_token_permissions_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "action",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "files",
    "indexes": [{
      "name": "upload_files_folder_path_index",
      "columns": ["folder_path"],
      "type": null
    }, {
      "name": "upload_files_created_at_index",
      "columns": ["created_at"],
      "type": null
    }, {
      "name": "upload_files_updated_at_index",
      "columns": ["updated_at"],
      "type": null
    }, {"name": "upload_files_name_index", "columns": ["name"], "type": null}, {
      "name": "upload_files_size_index",
      "columns": ["size"],
      "type": null
    }, {"name": "upload_files_ext_index", "columns": ["ext"], "type": null}, {
      "name": "files_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "files_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "files_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "files_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "alternative_text",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "caption",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "width",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "height",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "formats",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "hash",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "ext",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "mime",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "size",
      "type": "decimal",
      "args": [10, 2],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "url",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "preview_url",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "provider",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "provider_metadata",
      "type": "jsonb",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "folder_path",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "upload_folders",
    "indexes": [{
      "name": "upload_folders_path_id_index",
      "columns": ["path_id"],
      "type": "unique"
    }, {
      "name": "upload_folders_path_index",
      "columns": ["path"],
      "type": "unique"
    }, {
      "name": "upload_folders_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "upload_folders_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "upload_folders_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "upload_folders_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "path_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "path",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "up_permissions",
    "indexes": [{
      "name": "up_permissions_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "up_permissions_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "up_permissions_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "up_permissions_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "action",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "up_roles",
    "indexes": [{
      "name": "up_roles_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "up_roles_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "up_roles_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "up_roles_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "description",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "type",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "up_users",
    "indexes": [{
      "name": "up_users_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "up_users_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "up_users_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "up_users_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "username",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "email",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "provider",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "password",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "reset_password_token",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "confirmation_token",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "confirmed",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "blocked",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "i18n_locale",
    "indexes": [{
      "name": "i18n_locale_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "i18n_locale_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "i18n_locale_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "i18n_locale_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "code",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "store_listings",
    "indexes": [{
      "name": "store_listings_created_by_id_fk",
      "columns": ["created_by_id"]
    }, {"name": "store_listings_updated_by_id_fk", "columns": ["updated_by_id"]}],
    "foreignKeys": [{
      "name": "store_listings_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "store_listings_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "name",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "description",
      "type": "text",
      "args": ["longtext"],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "short_summary",
      "type": "text",
      "args": ["longtext"],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "cta_text",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "cta_url",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "is_active",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "publisher",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "publisher_url",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "is_native",
      "type": "boolean",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "slug",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "published_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "types",
    "indexes": [{"name": "types_created_by_id_fk", "columns": ["created_by_id"]}, {
      "name": "types_updated_by_id_fk",
      "columns": ["updated_by_id"]
    }],
    "foreignKeys": [{
      "name": "types_created_by_id_fk",
      "columns": ["created_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }, {
      "name": "types_updated_by_id_fk",
      "columns": ["updated_by_id"],
      "referencedTable": "admin_users",
      "referencedColumns": ["id"],
      "onDelete": "SET NULL"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "label",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "slug",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "updated_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "published_at",
      "type": "datetime",
      "args": [{"useTz": false, "precision": 6}],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "created_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "updated_by_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "admin_permissions_role_links",
    "indexes": [{
      "name": "admin_permissions_role_links_fk",
      "columns": ["permission_id"]
    }, {
      "name": "admin_permissions_role_links_inv_fk",
      "columns": ["role_id"]
    }, {
      "name": "admin_permissions_role_links_unique",
      "columns": ["permission_id", "role_id"],
      "type": "unique"
    }, {"name": "admin_permissions_role_links_order_inv_fk", "columns": ["permission_order"]}],
    "foreignKeys": [{
      "name": "admin_permissions_role_links_fk",
      "columns": ["permission_id"],
      "referencedColumns": ["id"],
      "referencedTable": "admin_permissions",
      "onDelete": "CASCADE"
    }, {
      "name": "admin_permissions_role_links_inv_fk",
      "columns": ["role_id"],
      "referencedColumns": ["id"],
      "referencedTable": "admin_roles",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "permission_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "role_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "permission_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "admin_users_roles_links",
    "indexes": [{
      "name": "admin_users_roles_links_fk",
      "columns": ["user_id"]
    }, {"name": "admin_users_roles_links_inv_fk", "columns": ["role_id"]}, {
      "name": "admin_users_roles_links_unique",
      "columns": ["user_id", "role_id"],
      "type": "unique"
    }, {
      "name": "admin_users_roles_links_order_fk",
      "columns": ["role_order"]
    }, {"name": "admin_users_roles_links_order_inv_fk", "columns": ["user_order"]}],
    "foreignKeys": [{
      "name": "admin_users_roles_links_fk",
      "columns": ["user_id"],
      "referencedColumns": ["id"],
      "referencedTable": "admin_users",
      "onDelete": "CASCADE"
    }, {
      "name": "admin_users_roles_links_inv_fk",
      "columns": ["role_id"],
      "referencedColumns": ["id"],
      "referencedTable": "admin_roles",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "user_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "role_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "role_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {"name": "user_order", "type": "double", "args": [], "defaultTo": null, "notNullable": false, "unsigned": true}]
  }, {
    "name": "strapi_api_token_permissions_token_links",
    "indexes": [{
      "name": "strapi_api_token_permissions_token_links_fk",
      "columns": ["api_token_permission_id"]
    }, {
      "name": "strapi_api_token_permissions_token_links_inv_fk",
      "columns": ["api_token_id"]
    }, {
      "name": "strapi_api_token_permissions_token_links_unique",
      "columns": ["api_token_permission_id", "api_token_id"],
      "type": "unique"
    }, {"name": "strapi_api_token_permissions_token_links_order_inv_fk", "columns": ["api_token_permission_order"]}],
    "foreignKeys": [{
      "name": "strapi_api_token_permissions_token_links_fk",
      "columns": ["api_token_permission_id"],
      "referencedColumns": ["id"],
      "referencedTable": "strapi_api_token_permissions",
      "onDelete": "CASCADE"
    }, {
      "name": "strapi_api_token_permissions_token_links_inv_fk",
      "columns": ["api_token_id"],
      "referencedColumns": ["id"],
      "referencedTable": "strapi_api_tokens",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "api_token_permission_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "api_token_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "api_token_permission_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "strapi_transfer_token_permissions_token_links",
    "indexes": [{
      "name": "strapi_transfer_token_permissions_token_links_fk",
      "columns": ["transfer_token_permission_id"]
    }, {
      "name": "strapi_transfer_token_permissions_token_links_inv_fk",
      "columns": ["transfer_token_id"]
    }, {
      "name": "strapi_transfer_token_permissions_token_links_unique",
      "columns": ["transfer_token_permission_id", "transfer_token_id"],
      "type": "unique"
    }, {
      "name": "strapi_transfer_token_permissions_token_links_order_inv_fk",
      "columns": ["transfer_token_permission_order"]
    }],
    "foreignKeys": [{
      "name": "strapi_transfer_token_permissions_token_links_fk",
      "columns": ["transfer_token_permission_id"],
      "referencedColumns": ["id"],
      "referencedTable": "strapi_transfer_token_permissions",
      "onDelete": "CASCADE"
    }, {
      "name": "strapi_transfer_token_permissions_token_links_inv_fk",
      "columns": ["transfer_token_id"],
      "referencedColumns": ["id"],
      "referencedTable": "strapi_transfer_tokens",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "transfer_token_permission_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "transfer_token_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "transfer_token_permission_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "files_related_morphs",
    "indexes": [{
      "name": "files_related_morphs_fk",
      "columns": ["file_id"]
    }, {
      "name": "files_related_morphs_order_index",
      "columns": ["order"],
      "type": null
    }, {"name": "files_related_morphs_id_column_index", "columns": ["related_id"], "type": null}],
    "foreignKeys": [{
      "name": "files_related_morphs_fk",
      "columns": ["file_id"],
      "referencedColumns": ["id"],
      "referencedTable": "files",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "file_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "related_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "related_type",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {
      "name": "field",
      "type": "string",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": false
    }, {"name": "order", "type": "double", "args": [], "defaultTo": null, "notNullable": false, "unsigned": true}]
  }, {
    "name": "files_folder_links",
    "indexes": [{"name": "files_folder_links_fk", "columns": ["file_id"]}, {
      "name": "files_folder_links_inv_fk",
      "columns": ["folder_id"]
    }, {
      "name": "files_folder_links_unique",
      "columns": ["file_id", "folder_id"],
      "type": "unique"
    }, {"name": "files_folder_links_order_inv_fk", "columns": ["file_order"]}],
    "foreignKeys": [{
      "name": "files_folder_links_fk",
      "columns": ["file_id"],
      "referencedColumns": ["id"],
      "referencedTable": "files",
      "onDelete": "CASCADE"
    }, {
      "name": "files_folder_links_inv_fk",
      "columns": ["folder_id"],
      "referencedColumns": ["id"],
      "referencedTable": "upload_folders",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "file_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "folder_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {"name": "file_order", "type": "double", "args": [], "defaultTo": null, "notNullable": false, "unsigned": true}]
  }, {
    "name": "upload_folders_parent_links",
    "indexes": [{
      "name": "upload_folders_parent_links_fk",
      "columns": ["folder_id"]
    }, {
      "name": "upload_folders_parent_links_inv_fk",
      "columns": ["inv_folder_id"]
    }, {
      "name": "upload_folders_parent_links_unique",
      "columns": ["folder_id", "inv_folder_id"],
      "type": "unique"
    }, {"name": "upload_folders_parent_links_order_inv_fk", "columns": ["folder_order"]}],
    "foreignKeys": [{
      "name": "upload_folders_parent_links_fk",
      "columns": ["folder_id"],
      "referencedColumns": ["id"],
      "referencedTable": "upload_folders",
      "onDelete": "CASCADE"
    }, {
      "name": "upload_folders_parent_links_inv_fk",
      "columns": ["inv_folder_id"],
      "referencedColumns": ["id"],
      "referencedTable": "upload_folders",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "folder_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "inv_folder_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "folder_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "up_permissions_role_links",
    "indexes": [{
      "name": "up_permissions_role_links_fk",
      "columns": ["permission_id"]
    }, {
      "name": "up_permissions_role_links_inv_fk",
      "columns": ["role_id"]
    }, {
      "name": "up_permissions_role_links_unique",
      "columns": ["permission_id", "role_id"],
      "type": "unique"
    }, {"name": "up_permissions_role_links_order_inv_fk", "columns": ["permission_order"]}],
    "foreignKeys": [{
      "name": "up_permissions_role_links_fk",
      "columns": ["permission_id"],
      "referencedColumns": ["id"],
      "referencedTable": "up_permissions",
      "onDelete": "CASCADE"
    }, {
      "name": "up_permissions_role_links_inv_fk",
      "columns": ["role_id"],
      "referencedColumns": ["id"],
      "referencedTable": "up_roles",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "permission_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "role_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "permission_order",
      "type": "double",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }]
  }, {
    "name": "up_users_role_links",
    "indexes": [{"name": "up_users_role_links_fk", "columns": ["user_id"]}, {
      "name": "up_users_role_links_inv_fk",
      "columns": ["role_id"]
    }, {
      "name": "up_users_role_links_unique",
      "columns": ["user_id", "role_id"],
      "type": "unique"
    }, {"name": "up_users_role_links_order_inv_fk", "columns": ["user_order"]}],
    "foreignKeys": [{
      "name": "up_users_role_links_fk",
      "columns": ["user_id"],
      "referencedColumns": ["id"],
      "referencedTable": "up_users",
      "onDelete": "CASCADE"
    }, {
      "name": "up_users_role_links_inv_fk",
      "columns": ["role_id"],
      "referencedColumns": ["id"],
      "referencedTable": "up_roles",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "user_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "role_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {"name": "user_order", "type": "double", "args": [], "defaultTo": null, "notNullable": false, "unsigned": true}]
  }, {
    "name": "store_listings_types_links",
    "indexes": [{
      "name": "store_listings_types_links_fk",
      "columns": ["store_listing_id"]
    }, {
      "name": "store_listings_types_links_inv_fk",
      "columns": ["type_id"]
    }, {
      "name": "store_listings_types_links_unique",
      "columns": ["store_listing_id", "type_id"],
      "type": "unique"
    }, {"name": "store_listings_types_links_order_fk", "columns": ["type_order"]}],
    "foreignKeys": [{
      "name": "store_listings_types_links_fk",
      "columns": ["store_listing_id"],
      "referencedColumns": ["id"],
      "referencedTable": "store_listings",
      "onDelete": "CASCADE"
    }, {
      "name": "store_listings_types_links_inv_fk",
      "columns": ["type_id"],
      "referencedColumns": ["id"],
      "referencedTable": "types",
      "onDelete": "CASCADE"
    }],
    "columns": [{
      "name": "id",
      "type": "increments",
      "args": [{"primary": true, "primaryKey": true}],
      "defaultTo": null,
      "notNullable": true,
      "unsigned": false
    }, {
      "name": "store_listing_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {
      "name": "type_id",
      "type": "integer",
      "args": [],
      "defaultTo": null,
      "notNullable": false,
      "unsigned": true
    }, {"name": "type_order", "type": "double", "args": [], "defaultTo": null, "notNullable": false, "unsigned": true}]
  }]
}
